from src.ui.view import timeline_compat

SCROLLBAR_WIDTH = 10
SCROLLBAR_MARGIN = 6
SCROLL_UNITS_PER_MEASURE = 1000
SELECTION_EDGE_MARGIN = 36
SELECTION_EDGE_INTERVAL_MS = 16
SELECTION_EDGE_SPEED = 0.04
MAX_VISIBLE_LOOKBACK_MEASURES = 32.0
TARGET_PLAYBACK_FPS = 120
PLAYBACK_REPAINT_INTERVAL_MS = max(1, round(1000 / TARGET_PLAYBACK_FPS))
MIN_SCROLL_SPEED = 1.0
MAX_SCROLL_SPEED = 20.0
PIXELS_PER_SCROLL_SPEED = timeline_compat.MEASURE_HEIGHT
DEFAULT_VIEW_LANE_WIDTH = 24.0
RIGHT_DRAG_THRESHOLD_PX = 4.0
