"""UI surface tokens and Qt helpers."""

from __future__ import annotations
from PySide6.QtGui import QColor


from functools import lru_cache

@lru_cache(maxsize=128)
def qt(value: str | tuple) -> QColor:
    """Create a QColor from a theme token."""
    if isinstance(value, tuple):
        if len(value) == 3:
            return QColor(*value)
        return QColor(*value)
    return QColor(value)


def with_alpha(color: QColor, alpha: int) -> QColor:
    """Copy a QColor and apply a theme alpha token."""
    copy = QColor(color)
    copy.setAlpha(alpha)
    return copy


# Primitives
TRANSPARENT = "transparent"
BLACK = "#000000"
WHITE = "#ffffff"

# Typography
FONT_UI = "Inter, system-ui, sans-serif"
FONT_MONO = "ui-monospace, 'JetBrains Mono', 'Roboto Mono', Menlo, Monaco, Consolas, monospace"

# Studio Palette
BASE_GRAY_900 = "#1a1a1a"  # Main Background
BASE_GRAY_850 = "#262626"  # Sidebar / Toolbars
BASE_GRAY_800 = "#323232"  # Hover / Selected
BASE_GRAY_750 = "#3a3a3a"  # Secondary Elevated
BASE_GRAY_700 = "#454545"  # Borders (Subtle)
BASE_GRAY_600 = "#555555"  # Muted Text / Borders
BASE_GRAY_400 = "#8e8e93"  # System Gray
BASE_GRAY_200 = "#c7c7cc"  # Secondary Text
BASE_GRAY_100 = "#f2f2f7"  # Primary Text (Off-white for soft look)

ACCENT_BLUE = "#0a84ff"     # System Blue (Dark)
ACCENT_BLUE_HOVER = "#409cff"
ACCENT_BLUE_PRESSED = "#0066cc"

# Legacy/Compatibility Mappings
VOID_BLACK = BASE_GRAY_900
DEEP_CHARCOAL = BASE_GRAY_850
GRAPHITE_700 = BASE_GRAY_800
GRAPHITE_600 = BASE_GRAY_850
GRAPHITE_500 = BASE_GRAY_700
GRAPHITE_400 = BASE_GRAY_600
SLATE_300 = BASE_GRAY_400
SLATE_200 = BASE_GRAY_200
ASH_50 = WHITE
SNOW = WHITE
EMBER_RED = "#ff453a"      # System Red (Dark)
MINT_SIGNAL = "#32d74b"    # System Green (Dark)
SKY_SIGNAL = ACCENT_BLUE

PITCH_BLACK = VOID_BLACK
GRAPHITE = DEEP_CHARCOAL
DEEP_SLATE = GRAPHITE_700
CHARCOAL_GREY = GRAPHITE_600
MUTED_ASH = GRAPHITE_500
GUNMETAL = GRAPHITE_400
PORCELAIN = SNOW
LIGHT_STEEL = SLATE_200
STORM_CLOUD = SLATE_300
FOG_GREY = SLATE_300
ALABASTER = ASH_50
AETHER_BLUE = SKY_SIGNAL

# Surfaces
APP_BACKGROUND = BASE_GRAY_900
SURFACE_RAISED = BASE_GRAY_850
SURFACE_NAV = BASE_GRAY_850
SURFACE_ELEVATED = BASE_GRAY_750
SURFACE_LIST_HOVER = BASE_GRAY_800
SURFACE_LIST_SELECTED = BASE_GRAY_800
SURFACE_SCROLLBAR = BASE_GRAY_900
SURFACE_SCROLLBAR_HANDLE = BASE_GRAY_700
SURFACE_SCROLLBAR_HANDLE_HOVER = BASE_GRAY_600
SURFACE_SELECTED = BASE_GRAY_800
SURFACE_MENU = BASE_GRAY_850
SURFACE_MENU_HOVER = BASE_GRAY_700
SURFACE_MENUBAR = BASE_GRAY_850
SURFACE_MENUBAR_HOVER = BASE_GRAY_800
SURFACE_STATUS_BUTTON = BASE_GRAY_800
SURFACE_STATUS_BUTTON_HOVER = BASE_GRAY_700
SURFACE_TIMELINE = BASE_GRAY_850
SURFACE_CHIP = "#2d2d2d"  # New: specifically for tag-like elements

# Borders
BORDER_PANEL = BASE_GRAY_700
BORDER_CONTROL = BASE_GRAY_600
BORDER_CONTROL_SOFT = BASE_GRAY_700
BORDER_STATUS = BASE_GRAY_700
BORDER_STATUS_BUTTON = BASE_GRAY_600
BORDER_CHIP = "#454545"  # Subtle border for chips, distinct from hover highlight

# Text
TEXT_PRIMARY = WHITE
TEXT_SOFT = WHITE
TEXT_MUTED = WHITE
TEXT_DIM = WHITE
TEXT_SUBTLE = BASE_GRAY_200
TEXT_EDITOR = WHITE
TEXT_MEASURE = WHITE
TEXT_STATUS_MUTED = WHITE
TEXT_DISABLED = BASE_GRAY_600
TEXT_TIMELINE = WHITE

# Accents
ACCENT = ACCENT_BLUE
ACCENT_HOVER = ACCENT_BLUE_HOVER
ACCENT_PRESSED = ACCENT_BLUE_PRESSED
ACCENT_PROGRESS = ACCENT_BLUE
ACCENT_TIMELINE_PLAYHEAD = WHITE
PRIMARY_ACTION_SURFACE = ACCENT_BLUE
PRIMARY_ACTION_SURFACE_HOVER = ACCENT_BLUE_HOVER
PRIMARY_ACTION_SURFACE_PRESSED = ACCENT_BLUE_PRESSED

# Overlays & Components
OVERLAY_PANEL_FILL = (26, 26, 26, 230)
OVERLAY_PANEL_BORDER = (255, 255, 255, 40)
SELECTION_FILL = (10, 132, 255, 50)
SELECTION_OUTLINE = ACCENT_BLUE

RADAR_GRID_OUTLINE = (255, 255, 255, 90)
RADAR_GRID_FILL = (26, 26, 26, 210)
RADAR_GRID_LINE = (255, 255, 255, 35)
RADAR_GRID_SPOKE = (255, 255, 255, 55)
RADAR_DATA_STROKE = ACCENT_BLUE
RADAR_DATA_FILL = (10, 132, 255, 70)
RADAR_LABEL_SHADOW = BLACK

LANE_LINE = (69, 69, 69)
TIMELINE_LINE = (110, 110, 110)
ATTACHMENT_WARNING = (255, 69, 58)
WARNING_RED = EMBER_RED


